name: Publish Packages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore src/ConfigView.csproj
    - name: Build
      run: dotnet build src/ConfigView.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test tests/ConfigView.Tests.csproj
    - name: Publish ConfigView
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/ConfigView.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
